---
name: Unit Tests
on:
  push:
    branches:
      - '**'

jobs:
  macos-debug:
    name: MacOS Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Debug Build
        run: cmake -S . -B cmake-build-debug
      - name: Build Debug Build
        run: cmake --build cmake-build-debug --target omega_test
      - name: Run Tests
        run: |
          cd cmake-build-debug/src/tests/
          ./omega_test -d yes --order lex

  linux-debug:
    name: Linux Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Valgrind
        run: sudo apt install -y valgrind
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Debug Build
        run: cmake -S . -B cmake-build-debug
      - name: Build Debug Build
        run: cmake --build cmake-build-debug
      - name: Run Tests
        run: |
          cd cmake-build-debug/src/tests/
          ./omega_test -d yes --order lex
      - name: Run Tests Under Valgrind
        run: |
          cd cmake-build-debug/src/tests/
          valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./omega_test -d yes --order lex


  windows-debug:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            mingw-w64-${{ matrix.env }}-toolchain
            base-devel
            cmake
            doxygen
            swig
            git
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Debug Build
        run: cmake -S . -B cmake-build-debug
      - name: Build Debug Build
        run: cmake --build cmake-build-debug
      - name: Run Tests
        run: |
          cd cmake-build-debug/src/tests/
          ./omega_test -d yes --order lex
